version: '3.6'
services:
  postgres:
    image: postgres
    container_name: dejavu_postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.2
    container_name: dejavu_graphql
    network_mode: "host"
    # ports:
    #   - '8081:8081'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@localhost:5433/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_REMOTE_SCHEMA: http://localhost:4000/graphql
      HASURA_GRAPHQL_ACCESS_KEY: 'test'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'anonymous'
      HASURA_GRAPHQL_JWT_SECRET: '{
  "type":"RS512",
  "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
}'
volumes:
  db_data:
